config/routes.rb
Rails.application.routes.draw do
  root 'tops#top'
  #devise_for :users
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  resources :memos

#  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
#  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  mount_uploader :icon, IconUploader
  validates:title, presence:true
  validates:content, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :authentication_keys => [:name]

  #nameを必須とする
  validates_uniqueness_of :name
  validates_presence_of :name

  #nameを利用してログインするようにオーバーライド
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      #認証の条件式を変更する
      where(conditions).where(["name = :value", { :value => name }]).first
    else
      where(conditions).first
    end
  end

  #emailを不要とする
  def email_required?
    false
  end

  def email_changed?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email,:encrypted_password])
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  
  def index
    @memos = Memo.all
    @search = Memo.search(params[:q]) 
    @memos = @search.result 

    respond_to do |format|
      format.html
      format.json { render json: @memos }
    end

  end
  
  def show
  end

  def new
    @memo = Memo.new
  end

  def edit
  end

  def create
    @memo = Memo.new(memo_params)

    respond_to do |format|
      if @memo.save
        TitlesChangeJob.perform_later(@memo.id)
        format.html { redirect_to memos_path } 
        format.json { render :show, status: :created, location: @memo }
      else
        format.html { render :new }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @memo.update(memo_params)
        TitlesChangeJob.perform_later(@memo.id)
        format.html { redirect_to memos_path } 
        format.json { render :show, status: :ok, location: @memo }
      else
        format.html { render :edit }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @memo.destroy
    respond_to do |format|
      format.html { redirect_to memos_path } 
      format.json { head :no_content }
    end
  end

  private
  
    def set_memo
      @memo = Memo.find(params[:id])
    end

    def memo_params
      params.require(:memo).permit(:title, :content, :icon)
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def top
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
#   def new
#     super
#   end

  # POST /resource/confirmation
#   def create
#     super
#   end

  # GET /resource/confirmation?confirmation_token=abcdef
#   def show
#     super
#   end

#   protected

  # The path used after resending confirmation instructions.
#   def after_resending_confirmation_instructions_path_for(resource_name)
#     super(resource_name)
#   end

  # The path used after confirmation.
#   def after_confirmation_path_for(resource_name, resource)
#     super(resource_name, resource)
#   end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
#   def new
#     super
#   end

  # POST /resource/password
#   def create
#     super
#   end

  # GET /resource/password/edit?reset_password_token=abcdef
#   def edit
#     super
#   end

  # PUT /resource/password
#   def update
#     super
#   end

#   protected

#   def after_resetting_password_path_for(resource)
#     super(resource)
#   end

  # The path used after sending reset password instructions
#   def after_sending_reset_password_instructions_path_for(resource_name)
#     super(resource_name)
#   end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
#   before_action :configure_sign_up_params, only: [:create]
#   before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
#   def new
#     super
#   end

  # POST /resource
#   def create
#     super
#   end

  # GET /resource/edit
#   def edit
#     super
#   end

  # PUT /resource
#   def update
#     super
#   end

  # DELETE /resource
#   def destroy
#     super
#   end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
#   def cancel
#     super
#   end

#   protected

  # If you have extra params to permit, append them to the sanitizer.
#   def configure_sign_up_params
#     devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
#   end

  # If you have extra params to permit, append them to the sanitizer.
#   def configure_account_update_params
#     devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
#   end

  # The path used after sign up.
#   def after_sign_up_path_for(resource)
#     super(resource)
#   end

  # The path used after sign up for inactive accounts.
#   def after_inactive_sign_up_path_for(resource)
#     super(resource)
#   end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
#   before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
#   def new
#     super
#   end

  # POST /resource/sign_in
#   def create
#     super
#   end

  # DELETE /resource/sign_out
#   def destroy
#     super
#   end

#   protected

  # If you have extra params to permit, append them to the sanitizer.
#   def configure_sign_in_params
#     devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
#   end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
   #GET /resource/unlock/new
   def new
     super
   end

   #POST /resource/unlock
   def create
     super
   end

   #GET /resource/unlock?unlock_token=abcdef
   def show
     super
   end

   protected

  # The path used after sending unlock password instructions
   def after_sending_unlock_instructions_path_for(resource)
     super(resource)
   end

  # The path used after unlocking the resource
   def after_unlock_path_for(resource)
     super(resource)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>GraduateApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
  </head>

  <body>
    <header>
      <div class="header-logo">
        <li><%= link_to "OnlineSimpleMemo", root_path %></li>
      </div>
      <div class="drawer_menu">
        <div class="drawer_bg"></div>
          <button type="button" class="drawer_button">
            <span class="drawer_bar drawer_bar1"></span>
            <span class="drawer_bar drawer_bar2"></span>
            <span class="drawer_bar drawer_bar3"></span>
            <span class="drawer_menu_text drawer_text">MENU</span>
            <span class="drawer_close drawer_text">CLOSE</span>
          </button>
        <nav class="drawer_nav_wrapper">
          <ul class="drawer_nav">
            <% if user_signed_in? %>
              <li><%= link_to "新規作成", new_memo_path %></li>
              <li><%= link_to 'メモ一覧', memos_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              <li><%= "#{current_user.name}"%></li>
            <% else %>
              <li><%= link_to "新規登録", new_user_registration_path %></li>
              <li><%= link_to "ログイン", new_user_session_path %></li>
            <% end %>
            <% if notice %>
              <p class="alert alert-notice"><%= notice %></p>
            <% end %>
            <% if alert %>
              <p class="alert alert-error"><%= alert %></p>
            <% end %>
          </ul>
        </nav>
      </div>
<!-- jQuery読み込み -->
      <script src="https://code.jquery.com/jquery-1.9.1.min.js" type="text/javascript"></script>
      <script>
        $(function () {
	
	      $('.drawer_button').click(function () {
		      $(this).toggleClass('active');
		      $('.drawer_bg').fadeToggle();
		      $('nav').toggleClass('open');
	      })
	      $('.drawer_bg').click(function () {
		      $(this).fadeOut();
		      $('.drawer_button').removeClass('active');
		      $('nav').removeClass('open');
	      });
         })
      </script>
    </header>

    <%= yield %>
  </body>
</html>

app/views/memos/_form.html.erb
<div class="main posts-new">
  <div class="container">

  <%= form_with(model: memo, local: true) do |form| %>
    <div class="form">
      <div class="form-body">
        <% if memo.errors.any? %>
          <div id="error_explanation">
            <h4><%= pluralize(memo.errors.count, "件のエラー") %></h4>
            <ul>
              <% memo.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :タイトル %>
          <%= form.text_field :title, id: :memo_title %>
        </div>

        <div class="field">
          <%= form.label :内容 %>
          <%= form.text_area :content, id: :memo_content %><br>
          文字数：<span class="count">0</span>
          <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
          <script type="text/javascript">
            $(function(){
              $('textarea').bind('keydown keyup keypress change',function(){
                var thisValueLength = $(this).val().length;
              $('.count').html(thisValueLength);
                });
            });
          </script>
        </div>

        <div class="field">
          <%= form.label :画像登録 %><br>
          <%= form.file_field :icon, id: :memo_icon %>
        </div>
        
        <div class="actions">
          <%= form.submit "保存"  %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/memos/edit.html.erb
<%= render 'form', memo: @memo %>

app/views/memos/index.html.erb
<div class="main">
  <div class="search">
    <%= search_form_for @search do |f| %>
      <div class="search_title">
        <%= f.label :title_cont, "タイトル" %>
        <%= f.text_field :title_cont, :placeholder =>"タイトル" %>
      </div>
      <div class="search_time">
        <%= f.label :created_at, '年月日' %>
        <%= f.date_select :created_at_gteq, include_blank: true %>〜
        <%= f.date_select :created_at_lteq, include_blank: true %>
      </div>
      <div class="search_button">
        <%= f.submit '検索する' %>
      </div>
    <% end %>
  </div>
  
  <div class="container">
    <div id="menu-list">
      <ul>
        <li><%= sort_link(@search, :title, 'タイトルでソート') %></li>
        <li><%= sort_link(@search, :updated_at, '更新日時でソート') %></li>
      </ul>
    </div>

    <% @memos.each do |memo| %>
    <div class="posts-index-flame">
      <div class="post-flame">
        <div class="post-contents">
          <div class="memo-icon">
            <%= image_tag memo.icon %>
          </div>
          <div class="memo-title">
            <%= link_to memo.title, "/memos/#{memo.id}" %>
          </div>
          <div class="memo-update">
            <%= memo.updated_at.strftime('%Y/%m/%d %H:%M') %>
          </div>
        </div>
        <div class="contents-button">
          <%= link_to '削除', memo, method: :delete, data: { confirm: '本当に削除しますか?' } %>
          <%= link_to '編集', edit_memo_path(memo) %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/memos/new.html.erb
<%= render 'form', memo: @memo %>

app/views/memos/show.html.erb
<div class="main posts-new">
  <div class="container">
    <div class="form">
      <div class="form-body">
        <div class="field">
          <%= image_tag @memo.icon %><%= "タイトル：#{@memo.title}" %>
        </div>
          <p>内容</p>
        <div class="show-field">
          <%= @memo.content %>
        </div>
          <p><%= "文字数：#{@memo.content.size}" %></p>
        <div class="contents-button">
          <%= link_to '削除', memo_path, method: :delete, data: { confirm: '本当に削除しますか?' } %>
          <%= link_to '編集', edit_memo_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tops/top.html.erb
<div class="main top-main">
  <div class="top-message">
    <h2>This is "Online Simple Memo" </h2>
    <p>You can save your memo on the Web</p>
  </div>
</div>